# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('is_select', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lun_bo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('track_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('identifier', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_f1_shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('sc', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('img5', models.CharField(max_length=100)),
                ('s1', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
                ('s3', models.CharField(max_length=100)),
                ('s4', models.CharField(max_length=100)),
                ('s5', models.CharField(max_length=100)),
                ('c1', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=6)),
                ('num', models.IntegerField()),
                ('id_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=256)),
                ('imgRoot', models.CharField(default='1.jpg', max_length=256)),
                ('token', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sport_f1_shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Sport_f1_shoes'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Sport_f1_shoes'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
