# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
