# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgRoot',
            field=models.CharField(default='1.jpg', max_length=256),
        ),
    ]
