# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_imgroot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
            ],
        ),
    ]
