# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_goodsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lun_bo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('track_id', models.CharField(max_length=20)),
            ],
        ),
    ]
