# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_lun_bo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_f3_shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('sc', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('img5', models.CharField(max_length=100)),
                ('s1', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
                ('s3', models.CharField(max_length=100)),
                ('s4', models.CharField(max_length=100)),
                ('s5', models.CharField(max_length=100)),
                ('c1', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=6)),
                ('num', models.IntegerField()),
                ('id_num', models.IntegerField()),
            ],
        ),
    ]
