# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sport_f3_shoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sport_f3_shoes',
            new_name='Sport_f1_shoes',
        ),
    ]
