# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181104_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('is_select', models.BooleanField(default=True)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Sport_f1_shoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
